# Generated by Django 3.1.13 on 2022-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220828_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rasm',
            field=models.FileField(upload_to='media'),
        ),
    ]
