# Generated by Django 3.1.13 on 2022-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220828_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rasm',
            field=models.FileField(upload_to='media/'),
        ),
    ]
