# Generated by Django 3.1.13 on 2022-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220902_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rasm',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
