# Generated by Django 3.1.13 on 2022-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220902_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(null=True, upload_to='media/')),
                ('goshtn', models.CharField(max_length=200)),
                ('gosht', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Qoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(null=True, upload_to='media/')),
                ('goshtn', models.CharField(max_length=200)),
                ('gosht', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quyon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(null=True, upload_to='media/')),
                ('goshtn', models.CharField(max_length=200)),
                ('gosht', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tovuq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(null=True, upload_to='media/')),
                ('goshtn', models.CharField(max_length=200)),
                ('gosht', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tuya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(null=True, upload_to='media/')),
                ('goshtn', models.CharField(max_length=200)),
                ('gosht', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='Mol',
        ),
    ]
