# Generated by Django 3.1.13 on 2022-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
    ]
