# Generated by Django 4.2.2 on 2023-06-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_mol_id_alter_mt_id_alter_ot_id_alter_qoy_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mol',
        ),
        migrations.DeleteModel(
            name='Ot',
        ),
        migrations.DeleteModel(
            name='Qoy',
        ),
        migrations.DeleteModel(
            name='Quyon',
        ),
        migrations.DeleteModel(
            name='Tovuq',
        ),
        migrations.DeleteModel(
            name='Tuya',
        ),
    ]
